import React from "react";
import Head from 'next/head'
import Link from "next/link";
import styles from '../styles/Home.module.css'

export async function getServerSideProps() {
    const response = await fetch('https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json')
    return {
        props: {
            pokemon: await response.json()
        }
    }
}

export default function Home({pokemon}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon Database</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1>Pokemon List</h1>
        {pokemon.length > 0 &&
            <main className={styles.grid}>
                {pokemon.map((poke) => (
                    <div className={styles.card} key={poke.id}>
                        <Link href={`/pokemon/${poke.id}`}>

                            <img
                                src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${poke.image}`}
                                alt={pokemon.name}
                            />
                            <h3>{poke.name}</h3>
                        </Link>
                    </div>))}
            </main>
        }
        {pokemon.length === 0 && (
            <h1 className='loading'>Loading ...</h1>
        )}

    </div>
  )
}
